import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>달코의 방</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>달코의 방</h1>
        </div>
      </main>
    </>
  )
}
